# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bead70195d6f15daf34c4ec48ef4408b8ebed888e45435a8841ceca95b83404911f65e6040975c58b43ca1a121505593bf01d6e3513591bfd704630cb7a590b4

test:
  secret_key_base: f4b52f13060e054169bb19c6fcf0c436b87227d0569f06e3f4ce2a1cbe83f60f467a0d016ca9f487c7b850da06b33524e87a355dd626c89173924037842eb6e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
